name: "Pull Request Build"
description: "Build Docker image to specified target for pull request validation"
inputs:
  working-directory:
    description: 'The path to the working directory'
    required: false
    default: '.'
  docker-file:
    description: 'The path to the Dockerfile'
    required: true
  docker-file-target:
    description: 'The target step in the Dockerfile to run'
    required: true
  use-registry-cache:
    description: 'Enable registry-based build cache for faster builds'
    required: false
    default: 'false'
  app-name:
    description: 'The name of the app (used for cache scoping)'
    required: false
    default: ''
  acr-registry:
    description: 'The name of the ACR registry for build cache'
    required: false
    default: ''
  azure-service-principal-id:
    description: 'The ID of the service principal for registry authentication'
    required: false
    default: ''
  azure-service-principal-password:
    description: 'The password of the service principal for registry authentication'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Login to ACR for build cache
      if: inputs.use-registry-cache == 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.acr-registry }}.azurecr.io
        username: ${{ inputs.azure-service-principal-id }}
        password: ${{ inputs.azure-service-principal-password }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image for testing
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.working-directory }}
        file: ${{ inputs.working-directory }}/${{ inputs.docker-file }}
        target: ${{ inputs.docker-file-target }}
        push: false
        load: true
        cache-from: ${{ inputs.use-registry-cache == 'true' && format('type=registry,ref={0}.azurecr.io/{1}:buildcache', inputs.acr-registry, inputs.app-name) || '' }}
        cache-to: ${{ inputs.use-registry-cache == 'true' && format('type=registry,ref={0}.azurecr.io/{1}:buildcache,mode=max', inputs.acr-registry, inputs.app-name) || '' }}