name: "Pull Request Build"
description: "Build Docker image to specified target for pull request validation"
inputs:
  working-directory:
    description: 'The path to the working directory'
    required: false
    default: '.'
  docker-file:
    description: 'The path to the Dockerfile'
    required: true
  docker-file-target:
    description: 'The target step in the Dockerfile to run'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image for testing
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.working-directory }}
        file: ${{ inputs.working-directory }}/${{ inputs.docker-file }}
        target: ${{ inputs.docker-file-target }}
        push: false
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max